### ISSUE TITLE
yml 파일로 minikube 컨테이너 배포하기

### ISSUE THREAD

**Issue by hooniegit** [hooniegit/round-robin-practices#11]
### compose.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hoonieblog
  template:
    metadata:
      labels:
        app: hoonieblog
    spec:
      containers:
        - name: hoonieblog-httpd
          image: hoonie28/blog:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 4474
      targetPort: 80

  selector:
    app: hoonieblog
```

## 배포 명령어
```
$ kubectl apply -f compose.yml
```
