### ISSUE TITLE
[v1.0.0] Docker Compose로 라운드 로빈 컨테이너 구성하기

### ISSUE THREAD

**Issue by hooniegit** [hooniegit/round-robin-practices#9]
# 실습 내용

### docker-compose/base/docker-compose.yml 내용 수정하기

```
# 이름과 버전을 각자 원하는 방향으로 수정
name: hooniegit
version: "1.0.0"
services:
  blog:
    build: ../../httpd
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    ports:
      - 80
  
  load_balancer:
    build: ../../nginX
    # 포트 번호를 각자 원하는 방향으로 수정
    ports:
      - 9999:80
    depends_on:
      - blog
```

### httpd/Dockerfile 내용 수정하기

```
FROM httpd:2.4.57

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

RUN ["apt-get", "install", "-y",  "git"]
# 'hooniegit.github.io' 부분을 각자의 github 디렉토리로 수정
RUN ["git", "clone", "https://github.com/hooniegit/hooniegit.github.io.git", "/usr/local/apache2/app/blog/hooniegit.github.io"]

RUN ["apt-get", "install", "-y", "cron"]
COPY ["pull.sh", "/usr/local/apache2/app/blog/"]
COPY ["blog-pull-cronjob", "/etc/cron.d/blog-pull-cronjob"]
RUN crontab /etc/cron.d/blog-pull-cronjob

# 'hooniegit.github.io' 부분을 각자의 github 디렉토리로 수정
RUN sed -i 's#DocumentRoot "/usr/local/apache2/htdocs"#DocumentRoot "/usr/local/apache2/app/blog/hooniegit.github.io"#g' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's#<Directory "/usr/local/apache2/htdocs">#<Directory "/usr/local/apache2/app/blog/hooniegit.github.io">#g' /usr/local/apache2/conf/httpd.conf

CMD service cron start;httpd-foreground
```

### nginX/default.conf 내용 수정하기

```
# 블로그 이름 변경하기
# 스케일링할 개수에 맞추어 블로그 개수 변경하기
upstream blog_servers {
        server hooniegit-blog-1:80;
        server hooniegit-blog-2:80;
        server hooniegit-blog-3:80;
        server hooniegit-blog-4:80;
        server hooniegit-blog-5:80;
}

server {
        listen 80;

    location / {
        proxy_pass http://blog_servers;
    }
}
```

# 시작 명령어 - docker-compose 파일이 있는 위치에서 실행

```
# 블로그 개수는 사전에 설정한 blog_servers 에 맞추어 실행
$ docker compose up -d --scale blog=5

# 도커 상태 확인하기
$ docker ps
```
